//! GR6J model flux outputs.
//!
//! Single-timestep fluxes -- returned by `step()`.
//! `FluxesTimeseries` is auto-generated by the `Fluxes` derive macro.

use pydrology_macros::Fluxes;

use crate::traits::FluxesTimeseriesOps;

/// Single-timestep fluxes — returned by `step()`.
#[derive(Debug, Clone, Copy, Fluxes)]
pub struct Fluxes {
    pub pet: f64,
    pub precip: f64,
    pub production_store: f64,
    pub net_rainfall: f64,
    pub storage_infiltration: f64,
    pub actual_et: f64,
    pub percolation: f64,
    pub effective_rainfall: f64,
    pub q9: f64,
    pub q1: f64,
    pub routing_store: f64,
    pub exchange: f64,
    pub actual_exchange_routing: f64,
    pub actual_exchange_direct: f64,
    pub actual_exchange_total: f64,
    pub qr: f64,
    pub qrexp: f64,
    pub exponential_store: f64,
    pub qd: f64,
    pub streamflow: f64,
}

impl FluxesTimeseriesOps<Fluxes> for FluxesTimeseries {
    fn with_capacity(n: usize) -> Self {
        FluxesTimeseries::with_capacity(n)
    }
    fn push(&mut self, f: &Fluxes) {
        FluxesTimeseries::push(self, f);
    }
    fn len(&self) -> usize {
        FluxesTimeseries::len(self)
    }
    fn is_empty(&self) -> bool {
        FluxesTimeseries::is_empty(self)
    }
}
