/// GR2M model flux outputs.
///
/// Single-timestep fluxes -- returned by `step()`.
/// `FluxesTimeseries` is auto-generated by the `Fluxes` derive macro.
use pydrology_macros::Fluxes;

use crate::traits::FluxesTimeseriesOps;

#[derive(Debug, Clone, Copy, Fluxes)]
pub struct Fluxes {
    pub pet: f64,              // MISC(1)  — potential ET [mm/month]
    pub precip: f64,           // MISC(2)  — precipitation [mm/month]
    pub production_store: f64, // MISC(3)  — store level after timestep [mm]
    pub rainfall_excess: f64,  // MISC(4)  — P1 [mm/month]
    pub storage_fill: f64,     // MISC(5)  — PS [mm/month]
    pub actual_et: f64,        // MISC(6)  — AE [mm/month]
    pub percolation: f64,      // MISC(7)  — P2 [mm/month]
    pub routing_input: f64,    // MISC(8)  — P3 = P1 + P2 [mm/month]
    pub routing_store: f64,    // MISC(9)  — routing store after timestep [mm]
    pub exchange: f64,         // MISC(10) — AEXCH [mm/month]
    pub streamflow: f64,       // MISC(11) — Q [mm/month]
}

impl FluxesTimeseriesOps<Fluxes> for FluxesTimeseries {
    fn with_capacity(n: usize) -> Self {
        FluxesTimeseries::with_capacity(n)
    }
    fn push(&mut self, f: &Fluxes) {
        FluxesTimeseries::push(self, f);
    }
    fn len(&self) -> usize {
        FluxesTimeseries::len(self)
    }
    fn is_empty(&self) -> bool {
        FluxesTimeseries::is_empty(self)
    }
}
